# Generated by Django 5.1 on 2024-08-13 03:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipe_name', models.CharField(max_length=40)),
                ('recipe_type', models.CharField(max_length=40)),
                ('recipe_calories', models.IntegerField()),
                ('recipe_protein', models.IntegerField()),
                ('recipe_fat', models.IntegerField()),
                ('recipe_carbohydrates', models.IntegerField()),
                ('recipe_image', models.ImageField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ingredient_name', models.CharField(max_length=40)),
                ('ingredient_amount', models.CharField(max_length=40)),
                ('ingredient_alternatives', models.TextField(blank=True, null=True)),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mealmate.recipe')),
            ],
        ),
        migrations.CreateModel(
            name='RecipeInstructions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instructions', models.TextField()),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mealmate.recipe')),
            ],
        ),
    ]
