# Generated by Django 5.1 on 2024-08-13 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mealmate', '0002_alter_ingredient_recipe_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipeinstructions',
            name='instructions',
            field=models.TextField(blank=True, null=True),
        ),
    ]
